config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tweets

  resources :relationships

  get "profiles/:id" => "profiles#show", as: :profile

  get "profiles" => "profiles#index"

  root 'tweets#index'

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :user #This is the user that initiates the action
  belongs_to :friend, class_name: "User" #This is the user being followed
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user

  validates :message, presence: true, length: {maximum: 140, 
too_long: "A tweet is only 140 max. Everybody knows that!"}

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :relationships
  has_many :friends, through: :relationships

  # for paperclip!!

  validates :username, presence: true, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location) }

  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def index
  	@user = User.all
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
	def create
    	@relationship = current_user.relationships.build(:friend_id => params[:friend_id])
  		if @relationship.save
    		flash[:notice] = "Followed successfully."
    		redirect_to profile_path(current_user.id)
  		else
    		flash[:notice] = "Unable to follow."
    		redirect_to root_path
  		end
  	end

	def destroy
  		@relationship = current_user.relationships.find(params[:id])
  		@relationship.destroy
  		flash[:notice] = "No longer following."
  		redirect_to profile_path(current_user.id)
	end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def relationship_params
      params.require(:relationship).permit(:user_id, :friend_id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
	before_action :set_tweet, only: [:show, :edit, :update, :destroy]

	before_filter :authenticate_user!

	def create
    	@tweet = Tweet.new(tweet_params)

    	respond_to do |format|
      	if @tweet.save
        	format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
      	else
        	format.html { render :new }
      	end
    	end
	end

    def new
    	@tweet = Tweet.new
    end

    def show
    end

    def index
    	@t = Tweet.all
    end
    def update
    	respond_to do |format|
        	if @tweet.update(tweet_params)
          	format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
      		else
        	format.html { render :edit }
      		end
    	end
  	end
  	
  	def destroy
      @tweet.destroy
    	respond_to do |format|
      	format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
   		end
  	end


private
	def set_tweet
    	@tweet = Tweet.find(params[:id])
    end
    def tweet_params
    	params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/chrisforms/_cont.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="well">

app/views/chrisforms/_endcont.html.erb
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cwitter</title>
  
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" %>
  <%= csrf_meta_tags %>
  <link href='https://fonts.googleapis.com/css?family=Orbitron:400,500' rel='stylesheet' type='text/css'>
</head>
<body>
 <% if user_signed_in? %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Cweets", tweets_path, class: "navbar-brand" %>
</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "New Cweet", new_tweet_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
</li>
          <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <% else %>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-brand" %>
    </div>
  </div><!-- /.container-fluid -->
</nav>
                <% end %>

<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/profiles/index.html.erb
<h1>All Users<h1/>
<% @user.each do |user| %>
  <%= link_to user.username, profile_path(user) %> <br />
<% end %>

app/views/profiles/show.html.erb
<%= current_user.name%>
<h1><%= @user.username %>'s Profile</h1>

<% @user.tweets.each do |tweet| %>
  <%= tweet.message %> <br />
<% end %>

 <% if current_user.id != @user.id %>
	<% if current_user.friends.include?(@user) %>
    		<%= link_to "Unfollow", relationship_path(current_user.relationships.find_by_friend_id(@user)), :method => :delete %>	
  	<% else %>
   		 <%= link_to "Follow", relationships_path(:friend_id => @user), method: :post %>
  	<% end %>
  <% end %>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<p>
  <div class="field lookatmenow">
    <h4 class="barley"><%= f.label :message %></h4><br>
    <%= f.text_field :message %>
  </div>
</p>
  <div class="field cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions lookatmenow">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Post</h1>

<div class="row">
	<div class="col-md-6">
		<div class="well">
		<%= render 'form' %>
		</div>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>
</div>
</div>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="hops">Cwitters</h1>
<h2 class='malt'><i>"Cwitters Never Lose."</i></h2>

<div class="row">
<% @t.each do |x| %>
  <div class="col-md-6">
        <div class="well">
        <h3><strong><%= x.user.name %></strong> <%= link_to x.user.username, profile_path(x) %></h3>
        <h4><%= x.message %></h4>
        <h6><%= link_to 'Show', x %> | <%= link_to 'Edit', edit_tweet_path(x) %> | <%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' } %></h6>
      </div>
    </div>
    <% end %>
  </div>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Cweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
	<div class="col-md-6">
		<div class="well">
			<p><h2><%= @tweet.user.username %></h2></p>
  			<p><h4><%= @tweet.message %></h4></p>
  		</div>
<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>
	</div>
</div>